name: Generate CV PDFs
on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths:
      - '**.tex'

jobs:
  generate-cv-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: "tlmgr update --self && tlmgr install moderncv && tlmgr update --all"
          root_file: "*.tex"
          glob_root_file: true